### ISSUE TITLE
refine IDL

### ISSUE THREAD

**Issue by nuta** [resea/resea#2]
## `types.yml`
```yml
CString:
  type: alias
  alias_of: NullTermArray<Int8>
```

## `interfaces.yml`
```yml
an_interface:
  payloads:
    arg1:
      type: Int
      length_is: arg2
      default: 123
```
