### ISSUE TITLE
config

### ISSUE THREAD

**Issue by nuta** [resea/resea#20]
- serialized in Message Pack
- SDK embeds it into executable as `config_data`

```yml
includes:

config:
  foo:
    type:
    description:
    default:
    depends:
    includes:
```
